// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfQ7p3pTkC-0IPg0_hQhofcdz1SDQUGxM',
    appId: '1:385603776948:web:46f9a03f35e88078b482e1',
    messagingSenderId: '385603776948',
    projectId: 'sato-ai-b64a2',
    authDomain: 'sato-ai-b64a2.firebaseapp.com',
    storageBucket: 'sato-ai-b64a2.firebasestorage.app',
    measurementId: 'G-XMJNYZTXQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNXbGjcyYf1Dn_yWxiWrTBaav6NZ07Rlk',
    appId: '1:385603776948:android:fd0e8aaefec8b485b482e1',
    messagingSenderId: '385603776948',
    projectId: 'sato-ai-b64a2',
    storageBucket: 'sato-ai-b64a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD2hKNAItiFCrCLROJk9QnM3e90rvAcuE',
    appId: '1:385603776948:ios:64567f953327370db482e1',
    messagingSenderId: '385603776948',
    projectId: 'sato-ai-b64a2',
    storageBucket: 'sato-ai-b64a2.firebasestorage.app',
    iosClientId: '385603776948-rh4v7kh7g4t3n9jrgndpi4rlk2seuu2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD2hKNAItiFCrCLROJk9QnM3e90rvAcuE',
    appId: '1:385603776948:ios:64567f953327370db482e1',
    messagingSenderId: '385603776948',
    projectId: 'sato-ai-b64a2',
    storageBucket: 'sato-ai-b64a2.firebasestorage.app',
    iosClientId: '385603776948-rh4v7kh7g4t3n9jrgndpi4rlk2seuu2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfQ7p3pTkC-0IPg0_hQhofcdz1SDQUGxM',
    appId: '1:385603776948:web:822bfc5f94261e36b482e1',
    messagingSenderId: '385603776948',
    projectId: 'sato-ai-b64a2',
    authDomain: 'sato-ai-b64a2.firebaseapp.com',
    storageBucket: 'sato-ai-b64a2.firebasestorage.app',
    measurementId: 'G-6ND50VWJ87',
  );
}
